language: c
sudo: required
notifications:
  email: false
install:
  - make linux_install
script:
  - mkdir -p build
  - cc myInitializeMatrix.c -o build/myInitializeMatrix
  - cc -Ofast -pthread rowwise.c -o build/rowwise
  - cc -Ofast -pthread columnwise.c -o build/columnwise
  - make submission
