language: c
notifications:
  email: false
script:
  - mkdir -p build
  - cc myInitializeMatrix.c -o build/myInitializeMatrix
  - cc rowwise.c -o build/rowwise
  - cc -pthread columnwise.c -o build/columnwise
  - chmod 0755 run.sh
  - ./run.sh rowwise
  - ./run.sh columnwise
  - make zip
